"""artist engagement tables (T52)

Revision ID: 3978f11ad4da
Revises: d3f9a1c05b27
Create Date: 2026-07-13 18:40:27.787055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3978f11ad4da'
down_revision: Union[str, None] = 'd3f9a1c05b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The "ReactionType" Postgres enum type ALREADY EXISTS — the regular Reaction table (T11) created
# it. ArtistReaction reuses the same type, so we must reference it WITHOUT trying to create it
# again (create_type=False); otherwise `upgrade` fails with "type ReactionType already exists".
# For the same reason `downgrade` must not drop the type (Reaction still uses it) — dropping the
# table with create_type=False leaves the shared enum untouched.
reaction_type = postgresql.ENUM('HEART', 'FIRE', 'SPARKLE', name='ReactionType', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistComment',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('artistPostId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['artistPostId'], ['ArtistPost.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ArtistComment_artistPostId_idx', 'ArtistComment', ['artistPostId'], unique=False)
    op.create_table('ArtistReaction',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('artistPostId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('type', reaction_type, nullable=False),
    sa.ForeignKeyConstraint(['artistPostId'], ['ArtistPost.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ArtistReaction_artistPostId_userId_type_key', 'ArtistReaction', ['artistPostId', 'userId', 'type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ArtistReaction_artistPostId_userId_type_key', table_name='ArtistReaction')
    op.drop_table('ArtistReaction')
    op.drop_index('ArtistComment_artistPostId_idx', table_name='ArtistComment')
    op.drop_table('ArtistComment')
    # ### end Alembic commands ###
