"""add RateLimitHit table (T10)

Revision ID: bfb2538c1d89
Revises: c2a629aaeb84
Create Date: 2026-07-03 12:42:00.147467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfb2538c1d89'
down_revision: Union[str, None] = 'c2a629aaeb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RateLimitHit',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('RateLimitHit_subject_action_createdAt_idx', 'RateLimitHit', ['subject', 'action', 'createdAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('RateLimitHit_subject_action_createdAt_idx', table_name='RateLimitHit')
    op.drop_table('RateLimitHit')
    # ### end Alembic commands ###
