"""baseline: prisma schema (T05)

Revision ID: c2a629aaeb84
Revises:
Create Date: 2026-07-01 09:54:46.495894

WHAT THIS FILE IS
A "migration": a script that builds the database tables. This is the very first one
("the baseline"), so upgrade() creates all 14 tables and downgrade() removes them.
WHY it mostly runs itself: it was generated automatically from app/models.py, so we
don't hand-write these. On our existing database the tables were already created by
the old tool, so we "stamped" this as already-applied instead of re-running it; it
only actually runs when building a fresh, empty database (e.g. for a new developer).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2a629aaeb84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cluster',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('centroid', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('computedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Compatibility',
    sa.Column('userAId', sa.Text(), nullable=False),
    sa.Column('userBId', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('userAId', 'userBId')
    )
    op.create_index('Compatibility_userAId_idx', 'Compatibility', ['userAId'], unique=False)
    op.create_table('ModelMetrics',
    sa.Column('modelName', sa.Text(), nullable=False),
    sa.Column('silhouette', sa.Float(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('featureImportances', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('computedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('modelName')
    )
    op.create_table('Track',
    sa.Column('spotifyId', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artistName', sa.Text(), nullable=False),
    sa.Column('albumArtUrl', sa.Text(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('kaggleMatched', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('spotifyId')
    )
    op.create_table('User',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('supabaseUserId', sa.Text(), nullable=True),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('displayName', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('avatarUrl', sa.Text(), nullable=True),
    sa.Column('spotifyId', sa.Text(), nullable=True),
    sa.Column('isSynthetic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('isArtist', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('clusterId', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clusterId'], ['Cluster.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.create_index('User_handle_key', 'User', ['handle'], unique=True)
    op.create_index('User_spotifyId_key', 'User', ['spotifyId'], unique=True)
    op.create_index('User_supabaseUserId_key', 'User', ['supabaseUserId'], unique=True)
    op.create_table('ArtistPost',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('artistUserId', sa.Text(), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('linkedTrackId', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['artistUserId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ArtistPost_artistUserId_idx', 'ArtistPost', ['artistUserId'], unique=False)
    op.create_table('Follow',
    sa.Column('followerId', sa.Text(), nullable=False),
    sa.Column('followingId', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['followerId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['followingId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('followerId', 'followingId')
    )
    op.create_index('Follow_followingId_idx', 'Follow', ['followingId'], unique=False)
    op.create_table('Play',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('trackId', sa.Text(), nullable=False),
    sa.Column('playedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trackId'], ['Track.spotifyId'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Play_userId_idx', 'Play', ['userId'], unique=False)
    op.create_index('Play_userId_playedAt_key', 'Play', ['userId', 'playedAt'], unique=True)
    op.create_table('Post',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('trackId', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'SPOTIFY', name='PostSource'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['trackId'], ['Track.spotifyId'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Post_createdAt_idx', 'Post', ['createdAt'], unique=False)
    op.create_index('Post_userId_idx', 'Post', ['userId'], unique=False)
    op.create_table('SpotifyToken',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('accessToken', sa.Text(), nullable=False),
    sa.Column('refreshToken', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('TasteVector',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('computedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('UserStats',
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('topTracks', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('topArtists', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('topGenres', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('streakDays', sa.Integer(), nullable=False),
    sa.Column('totalPlays30d', sa.Integer(), nullable=False),
    sa.Column('computedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('Comment',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('postId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Comment_postId_idx', 'Comment', ['postId'], unique=False)
    op.create_table('Reaction',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('postId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('HEART', 'FIRE', 'SPARKLE', name='ReactionType'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['Post.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Reaction_postId_userId_type_key', 'Reaction', ['postId', 'userId', 'type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Reaction_postId_userId_type_key', table_name='Reaction')
    op.drop_table('Reaction')
    op.drop_index('Comment_postId_idx', table_name='Comment')
    op.drop_table('Comment')
    op.drop_table('UserStats')
    op.drop_table('TasteVector')
    op.drop_table('SpotifyToken')
    op.drop_index('Post_userId_idx', table_name='Post')
    op.drop_index('Post_createdAt_idx', table_name='Post')
    op.drop_table('Post')
    op.drop_index('Play_userId_playedAt_key', table_name='Play')
    op.drop_index('Play_userId_idx', table_name='Play')
    op.drop_table('Play')
    op.drop_index('Follow_followingId_idx', table_name='Follow')
    op.drop_table('Follow')
    op.drop_index('ArtistPost_artistUserId_idx', table_name='ArtistPost')
    op.drop_table('ArtistPost')
    op.drop_index('User_supabaseUserId_key', table_name='User')
    op.drop_index('User_spotifyId_key', table_name='User')
    op.drop_index('User_handle_key', table_name='User')
    op.drop_index('User_email_key', table_name='User')
    op.drop_table('User')
    op.drop_table('Track')
    op.drop_table('ModelMetrics')
    op.drop_index('Compatibility_userAId_idx', table_name='Compatibility')
    op.drop_table('Compatibility')
    op.drop_table('Cluster')
    # ### end Alembic commands ###
    # Alembic's auto-generated downgrade drops the tables but NOT the enum "types"
    # (PostSource, ReactionType) that Postgres created for the source/type columns.
    # Without this, tearing down and rebuilding a fresh database would fail on the
    # second build with "type already exists". checkfirst=True = "skip if missing".
    bind = op.get_bind()
    sa.Enum(name='PostSource').drop(bind, checkfirst=True)
    sa.Enum(name='ReactionType').drop(bind, checkfirst=True)
