"""analytics contract + medallion schemas (T39)

Revision ID: d3f9a1c05b27
Revises: bfb2538c1d89
Create Date: 2026-07-08

WHAT THIS MIGRATION DOES (T39 / ADR-0003 + ADR-0009):
- Creates the medallion schemas `bronze`, `silver`, `gold`.
- RELOCATES the existing `Track` + `Play` tables into `silver`, and `Cluster` + `ModelMetrics`
  into `gold`, using ALTER TABLE ... SET SCHEMA so the existing ROWS are preserved (we do NOT
  drop and recreate — that would lose data). Foreign keys follow the tables automatically.
- Drops the now-unused per-user analytics tables (`UserStats`, `TasteVector`, `Compatibility`)
  and the `User.clusterId` column — those values are computed on read now (ADR-0003). Nothing
  reads them yet, so the drops are safe.
- Adds `gold.ModelArtifact` (self-describing trained-model params) and the bronze raw landing
  tables `bronze.spotify_recently_played_raw` + `bronze.kaggle_tracks_raw`.

This revision is HAND-WRITTEN (not autogenerated): autogenerate would model the schema moves as
drop+create and lose data. Review the SQL, then apply with `uv run alembic upgrade head`.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3f9a1c05b27"
down_revision: Union[str, None] = "bfb2538c1d89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the medallion schemas.
    op.execute("CREATE SCHEMA IF NOT EXISTS bronze")
    op.execute("CREATE SCHEMA IF NOT EXISTS silver")
    op.execute("CREATE SCHEMA IF NOT EXISTS gold")

    # 2. Drop the unused per-user analytics tables + the User.clusterId link (computed on read now).
    #    Dropping the column also drops its foreign key to Cluster.
    op.drop_column("User", "clusterId")
    op.drop_table("UserStats")
    op.drop_table("TasteVector")
    op.drop_table("Compatibility")

    # 3. Relocate existing tables into their medallion schemas — SET SCHEMA preserves the rows and
    #    carries the constraints/indexes with the table.
    op.execute('ALTER TABLE "Track" SET SCHEMA silver')
    op.execute('ALTER TABLE "Play" SET SCHEMA silver')
    op.execute('ALTER TABLE "Cluster" SET SCHEMA gold')
    op.execute('ALTER TABLE "ModelMetrics" SET SCHEMA gold')

    # 4. New gold table: the self-describing model artifact (snake_case columns — a new table).
    op.create_table(
        "ModelArtifact",
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("feature_order", postgresql.JSONB(), nullable=False),
        sa.Column("scaler_mean", postgresql.JSONB(), nullable=False),
        sa.Column("scaler_std", postgresql.JSONB(), nullable=False),
        sa.Column("params", postgresql.JSONB(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("model_name"),
        schema="gold",
    )

    # 5. New bronze raw landing tables (append/immutable).
    op.create_table(
        "spotify_recently_played_raw",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bronze",
    )
    op.create_table(
        "kaggle_tracks_raw",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="bronze",
    )


def downgrade() -> None:
    # Reverse of upgrade. NOTE: recreating the dropped tables restores their STRUCTURE, not any
    # rows that existed before (they were unused, so there were none to lose).

    # Drop the tables added in upgrade.
    op.drop_table("kaggle_tracks_raw", schema="bronze")
    op.drop_table("spotify_recently_played_raw", schema="bronze")
    op.drop_table("ModelArtifact", schema="gold")

    # Move the relocated tables back to the default (public) schema.
    op.execute('ALTER TABLE gold."ModelMetrics" SET SCHEMA public')
    op.execute('ALTER TABLE gold."Cluster" SET SCHEMA public')
    op.execute('ALTER TABLE silver."Play" SET SCHEMA public')
    op.execute('ALTER TABLE silver."Track" SET SCHEMA public')

    # Recreate the dropped per-user analytics tables (matching the T05 baseline definitions).
    op.create_table(
        "Compatibility",
        sa.Column("userAId", sa.Text(), nullable=False),
        sa.Column("userBId", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("userAId", "userBId"),
    )
    op.create_index("Compatibility_userAId_idx", "Compatibility", ["userAId"], unique=False)
    op.create_table(
        "TasteVector",
        sa.Column("userId", sa.Text(), nullable=False),
        sa.Column("vector", postgresql.JSONB(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("computedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("userId"),
    )
    op.create_table(
        "UserStats",
        sa.Column("userId", sa.Text(), nullable=False),
        sa.Column("topTracks", postgresql.JSONB(), nullable=False),
        sa.Column("topArtists", postgresql.JSONB(), nullable=False),
        sa.Column("topGenres", postgresql.JSONB(), nullable=False),
        sa.Column("streakDays", sa.Integer(), nullable=False),
        sa.Column("totalPlays30d", sa.Integer(), nullable=False),
        sa.Column("computedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("userId"),
    )

    # Re-add the User.clusterId link.
    op.add_column("User", sa.Column("clusterId", sa.Text(), nullable=True))
    op.create_foreign_key(
        "User_clusterId_fkey", "User", "Cluster", ["clusterId"], ["id"],
        onupdate="CASCADE", ondelete="SET NULL",
    )

    # Drop the (now empty) medallion schemas.
    op.execute("DROP SCHEMA IF EXISTS gold")
    op.execute("DROP SCHEMA IF EXISTS silver")
    op.execute("DROP SCHEMA IF EXISTS bronze")
