# WHAT THIS FILE IS
# Alembic migration for T96: add a "createdAt" timestamp to the Reaction table.
# WHY: the "Liked by {most recent reactor}" line and the newest-first reactors list need
# reactions ordered by time, and Reaction's random cuid id can't provide that. The column is
# ADDITIVE (no data moves): server_default CURRENT_TIMESTAMP both backfills every existing
# row with the migration time and lets the database stamp future inserts automatically —
# matching how the other social tables' createdAt columns work (see models.py _created_at).
# Hand-written (not autogenerated) because it's one additive column; camelCase "createdAt"
# matches the table's existing Prisma-era column naming.

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4a2d81c96e0"
down_revision: Union[str, None] = "a1c47f9e2b30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL is safe in one step because server_default fills the value for every existing
    # row as the column is added (Postgres does this atomically for a constant-ish default).
    op.add_column(
        "Reaction",
        sa.Column(
            "createdAt",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )


def downgrade() -> None:
    op.drop_column("Reaction", "createdAt")
