"""text-only posts: nullable trackId/imageUrl/caption T104

Revision ID: fe4e66a13f08
Revises: f4a2d81c96e0
Create Date: 2026-07-23 10:06:25.499800

WHAT THIS FILE IS
Alembic migration for T104 (text-only posts). It only RELAXES three NOT NULL constraints so a
post can carry no media: Post.trackId (a regular post with no song), and ArtistPost.imageUrl /
ArtistPost.caption (an artist post with no photo / no words). Nothing is dropped or moved and no
data changes — every existing row already has these values, so this is fully backward-compatible
(the old media-required flow keeps working). The "you can't post nothing" rule is enforced in the
create endpoints, not by the database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe4e66a13f08'
down_revision: Union[str, None] = 'f4a2d81c96e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ArtistPost', 'imageUrl',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ArtistPost', 'caption',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('Post', 'trackId',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Post', 'trackId',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ArtistPost', 'caption',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ArtistPost', 'imageUrl',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
